// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navigation() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"border-b border-aged-ink/20 bg-parchment py-3\"><div class=\"container mx-auto px-4\"><div class=\"flex items-center justify-between\"><a href=\"/\" class=\"flex items-center gap-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 48 48\" class=\"w-8 h-8 text-aged-ink\" fill=\"currentColor\" aria-hidden=\"true\"><rect x=\"2\" y=\"2\" width=\"44\" height=\"44\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-dasharray=\"5 3\"></rect> <rect x=\"22\" y=\"33\" width=\"4\" height=\"9\" rx=\"1\"></rect> <ellipse cx=\"24\" cy=\"24\" rx=\"9\" ry=\"8\"></ellipse> <ellipse cx=\"16\" cy=\"28\" rx=\"7\" ry=\"6\"></ellipse> <ellipse cx=\"32\" cy=\"28\" rx=\"7\" ry=\"6\"></ellipse></svg> <span class=\"font-display text-xl font-bold text-aged-ink tracking-wide\">Saudade</span></a><div class=\"flex items-center gap-4\"><a href=\"/login\" class=\"px-5 py-2 rounded-md bg-terracotta text-white text-sm font-medium hover:bg-terracotta/80 transition-colors\">Login</a> <button aria-label=\"Open menu\" class=\"flex flex-col justify-center gap-1.5 p-1\"><span class=\"block w-6 h-0.5 bg-aged-ink rounded\"></span> <span class=\"block w-6 h-0.5 bg-aged-ink rounded\"></span> <span class=\"block w-6 h-0.5 bg-aged-ink rounded\"></span></button></div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
