// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"gothstarter/views/components"
	"gothstarter/views/layouts"
)

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><!-- Hero Section --><section class=\"container mx-auto px-4 py-20 text-center\"><h1 class=\"font-display text-5xl md:text-7xl font-bold text-aged-ink mb-6\">Cherished Memories</h1><p class=\"text-lg text-aged-ink/70 max-w-xl mx-auto mb-10\">A private, secure space for your family's roots — stories, records, and connections passed down through generations.</p><div class=\"flex flex-col sm:flex-row gap-4 justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.PrimaryButton("Add Photo").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SecondaryButton("Explore Stories").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></section><!-- Color Palette Section --><section class=\"container mx-auto px-4 py-12\"><h2 class=\"font-display text-2xl text-aged-ink mb-8 text-center\">Color Palette</h2><div class=\"flex flex-wrap justify-center gap-10\"><div class=\"flex flex-col items-center gap-2\"><div class=\"w-16 h-16 rounded-full bg-parchment border border-aged-ink/20 shadow-sm\"></div><span class=\"text-sm font-medium text-aged-ink\">Parchment</span> <span class=\"text-xs text-aged-ink/50\">#F4F1EA</span></div><div class=\"flex flex-col items-center gap-2\"><div class=\"w-16 h-16 rounded-full bg-aged-ink shadow-sm\"></div><span class=\"text-sm font-medium text-aged-ink\">Aged Ink</span> <span class=\"text-xs text-aged-ink/50\">#3E362E</span></div><div class=\"flex flex-col items-center gap-2\"><div class=\"w-16 h-16 rounded-full bg-terracotta shadow-sm\"></div><span class=\"text-sm font-medium text-aged-ink\">Faded Terracotta</span> <span class=\"text-xs text-aged-ink/50\">#C28B7E</span></div><div class=\"flex flex-col items-center gap-2\"><div class=\"w-16 h-16 rounded-full bg-sage shadow-sm\"></div><span class=\"text-sm font-medium text-aged-ink\">Faded Sage</span> <span class=\"text-xs text-aged-ink/50\">#8A9A86</span></div></div></section><!-- UI Elements Section --><section class=\"container mx-auto px-4 py-12 mb-12\"><h2 class=\"font-display text-2xl text-aged-ink mb-8 text-center\">UI Elements</h2><div class=\"flex flex-wrap justify-center gap-6 items-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.PrimaryButton("Add Photo").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SecondaryButton("View More").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button aria-label=\"Calendar\" class=\"p-3 rounded-lg border border-aged-ink/20 hover:bg-aged-ink/5 transition-colors text-aged-ink\"><i class=\"fa-regular fa-calendar text-xl\"></i></button> <button aria-label=\"Menu\" class=\"flex flex-col gap-1.5 p-3 rounded-lg border border-aged-ink/20 hover:bg-aged-ink/5 transition-colors\"><span class=\"block w-5 h-0.5 bg-aged-ink rounded\"></span> <span class=\"block w-5 h-0.5 bg-aged-ink rounded\"></span> <span class=\"block w-5 h-0.5 bg-aged-ink rounded\"></span></button></div></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
